userEmails = {
    "bertillecnt": "1@a.com",
    "juliadamon": "3@a.com",
    "soniaheartsfashion": "4@a.com",
    "anpaulinas": "5@a.com",
    "frenchgirldaily": "56@a.com",
    "daniellemetz": "64@a.com",
    "katherine_bondd": "68@a.com",
    "ohheylisa_": "69@a.com",
    "ceciliemoosgaard": "72@a.com",
    "ariadibari": "77@a.com",
    "heyhegia": "89@a.com",
    "parisianvibe": "91@a.com",
    "brit_harvey": "92@a.com",
    "juliesfi": "93@a.com",
    "ameliecheval31": "94@a.com",
    "katie.one": "95@a.com",
    "vivianeaudi": "96@a.com",
    "mariafedulova": "97@a.com",
    "elaisaya": "98@a.com",
    "noelledowning": "99@a.com",
    "javierittaaa": "100@a.com",
    "erikaaguileraa": "101@a.com",
    "oshawaiters": "102@a.com",
    "jessiefrizzell": "103@a.com",
    "paulinenavy": "104@a.com",
    "aliciabonora": "105@a.com",
    "amyfuchsia": "126@a.com",
    "itslibes": "107@a.com",
    "x_carms": "108@a.com",
    "sophiesuchan": "109@a.com",
    "larmoiredesoso": "110@a.com",
    "sabrinacsari": "111@a.com",
    "claudiagraziano": "112@a.com",
    "amandampn": "113@a.com",
    "freyakillin": "114@a.com",
    "taliacupcake": "115@a.com",
    "cerecampbell": "116@a.com",
    "annaastrup": "172@a.com",
    "chloemonchamp": "118@a.com",
    "michelleinfusino": "119@a.com",
    "poseandrepeat": "120@a.com",
    "lucyinthesskyy": "121@a.com",
    "okevaaa": "122@a.com",
    "bresheppard": "123@a.com",
    "nitsanraiter": "124@a.com",
    "emilyrosehannon": "125@a.com",
    "amyfuchsia": "126@a.com",
    "daniellemetz": "127@a.com",
    "callia_m": "128@a.com",
    "oliviabynature": "129@a.com",
    "chloehelenmiles": "134@a.com",
    "jenniferxlauren": "131@a.com",
    "yxcvanessa": "132@a.com",
    "marvadel": "133@a.com",
    "chloehelenmiles": "134@a.com",
    "ariadibari": "77@a.com",
    "linneafunks": "136@a.com",
    "modedamour": "15@a.com",
    "solenelara": "8@a.com",
    "lydiajanetomlinson": "139@a.com",
    "sandrarossi03": "140@a.com",
    "anoukyve": "141@a.com",
    "apollinethibault": "142@a.com",
    "fakerstrom": "143@a.com",
    "lauraslittlelocket": "144@a.com",
    "livia_auer": "145@a.com",
    "filippahagg": "146@a.com",
    "leasy_inparis": "147@a.com",
    "brittanybathgate": "148@a.com",
    "amaliemoosgaard": "149@a.com",
    "andicsinger": "150@a.com",
    "lestylealafrancaise": "151@a.com",
    "tendancehunter": "71@a.com",
    "_constance_d": "153@a.com",
    "rutaenroute": "154@a.com",
    "allchloerose": "155@a.com",
    "monikh": "156@a.com",
    "junybreeze": "157@a.com",
    "mon.agar": "158@a.com",
    "symphonyofsilk": "159@a.com",
    "kateehutchins": "84@a.com",
    "anouchkagauthier": "161@a.com",
    "lefevrediary": "162@a.com",
    "emmaleger": "81@a.com",
    "nojinasty": "164@a.com",
    "whatthephokelly": "66@a.com",
    "mariecher": "166@a.com",
    "lizarudkevich": "86@a.com",
    "violettevdvondel": "168@a.com",
    "ambervscott": "169@a.com",
    "mari_malibu": "170@a.com",
    "iliridakrasniqi": "171@a.com",
    "annaastrup": "172@a.com",
    "solenelara": "8@a.com",
    "marianne_theodorsen": "10@a.com",
    "igawysocka": "12@a.com",
    "sherlockdiary": "13@a.com",
    "lottefeyen": "14@a.com",
    "saarahkatharina": "16@a.com",
    "sarahchristine": "17@a.com",
    "aliissanaa": "18@a.com",
    "monika_potzy": "19@a.com",
    "chloehayward_": "20@a.com",
    "mildagud": "21@a.com",
    "barbarafavafmx": "22@a.com",
    "sophiepirrung": "23@a.com",
    "mademoisellelook": "25@a.com",
    "__ninaballerina__": "26@a.com",
    "anastasefi": "29@a.com",
    "karenxolea": "31@a.com",
    "trendyophelie": "32@a.com",
    "smythsisters": "33@a.com",
    "lolo_bravoo": "34@a.com",
    "ax_ouh": "35@a.com",
    "rubyholley_": "36@a.com",
    "amybethvdl": "37@a.com",
    "carotheresia": "38@a.com",
    "aurore_grd": "39@a.com",
    "entre_dois": "40@a.com",
    "barbarakristoffersen": "80@a.com",
    "emmaleger": "81@a.com",
    "josipellicano": "82@a.com",
    "alpa.rama": "83@a.com",
    "kateehutchins": "84@a.com",
    "jodielapetitefrenchie": "85@a.com",
    "lizarudkevich": "86@a.com",
    "nastyanastya": "87@a.com",
    "camilleyolaine": "88@a.com",
    "heyhegia": "89@a.com",
    "belajuliana_":"174@a.com",
    "victoriawaldau":"175@a.com",
    "emmanuellek_":"176@a.com",
    "shaniakufner_":"177@a.com",
    "amyz_k":"178@a.com",
    "saskia_freitas":"179@a.com",
    "jetamoure":"180@a.com",
    "asaqueenoffashion":"181@a.com",
    "ootdsubmit":"182@a.com",
    "ootdmagazine":"183@a.com",
    "blakehealey":"184@a.com",
    "ruby190":"185@a.com",
    "bethanmccoy":"186@a.com",
    "helenacritchley":"187@a.com",
    "sophieottewell":"188@a.com",
    "sarahjoholder":"189@a.com",
    "charliemariedoe":"190@a.com",
    "lradwell":"191@a.com",
    "festus.marika":"192@a.com",
    "salmabe__":"193@a.com",
    "itsbee____":"194@a.com",
    "dbzdutch":"195@a.com",
    "pinkbesos_":"196@a.com",
    "shayzanco_":"197@a.com",
    "janaegirard":"198@a.com",
    "____mkay":"199@a.com",
    "98smlc":"200@a.com",
    "michellejulietnaylaa":"201@a.com",
    "maryalicejenni":"202@a.com",
    "sandra_salic":"203@a.com",
    "baystayfit":"204@a.com",
    "simona.julia":"205@a.com",
    "margusha____":"206@a.com",
    "lenasaibel":"207@a.com",
    "lulouisaa":"208@a.com",
    "annchristiiiin":"209@a.com",
    "monmccallion":"210@a.com",
    "syd.and.ash":"211@a.com"
}

newuser = ["poseandrepeat","brit_harvey","michelleinfusino","vivianeaudi","amandampn","cerecampbell","annaastrup","michelleinfusino","chloemonchamp","oliviabynature","belajuliana_","mari_malibu","victoriawaldau","emmanuellek_","shaniakufner_","amyz_k","saskia_freitas","jetamoure","asaqueenoffashion","ootdsubmit","ootdmagazine","juliadamon","soniaheartsfashion","anpaulinas","daniellemetz","katherine_bondd","ohheylisa_","mariafedulova","paulinenavy","jessiefrizzell","aliciabonora","amyfuchsia","aliciabonora","amyfuchsia","itslibes","x_carms","freyakillin","taliacupcake","okevaaa","bresheppard","nitsanraiter","amyfuchsia","jenniferxlauren","blakehealey","ruby190","bethanmccoy","helenacritchley","sophieottewell","sarahjoholder","charliemariedoe","lradwell","festus.marika","salmabe__","itsbee____","dbzdutch","noelledowning","javierittaaa","erikaaguileraa","oshawaiters","pinkbesos_","shayzanco_","janaegirard","____mkay","98smlc","michellejulietnaylaa","maryalicejenni","sandra_salic","baystayfit","heyhegia","bertillecnt","frenchgirldaily","ceciliemoosgaard","ariadibari","parisianvibe","juliesfi","ameliecheval31","elaisaya","solenelara","chloehelenmiles","larmoiredesoso","sabrinacsari","claudiagraziano","yxcvanessa","marvadel","linneafunks","modedamour","lydiajanetomlinson","sandrarossi03","anoukyve","apollinethibault","fakerstrom","lauraslittlelocket","livia_auer","filippahagg","leasy_inparis","andicsinger","lestylealafrancaise","tendancehunter","lucyinthesskyy","katie.one","emilyrosehannon","callia_m","simona.julia","margusha____","lenasaibel","lulouisaa","annchristiiiin"]

# Fresh = ["belajuliana_",
# "victoriawaldau",
# "emmanuellek_",
# "shaniakufner_",
# "amyz_k",
# "saskia_freitas",
# "jetamoure",
# "asaqueenoffashion",
# "ootdsubmit",
# "ootdmagazine",
# "blakehealey",
# "ruby190",
# "bethanmccoy",
# "helenacritchley",
# "sophieottewell",
# "sarahjoholder",
# "charliemariedoe",
# "lradwell",
# "festus.marika",
# "salmabe__",
# "itsbee____",
# "dbzdutch",
# "pinkbesos_",
# "shayzanco_",
# "janaegirard",
# "____mkay",
# "98smlc",
# "michellejulietnaylaa",
# "maryalicejenni",
# "sandra_salic",
# "baystayfit",
# "simona.julia",
# "margusha____",
# "lenasaibel",
# "lulouisaa",
# "annchristiiiin"]

Fresh = ["monmccallion",
         "syd.and.ash"]

if __name__ == "__main__":
    index = 210
    for u in newuser:
        if not userEmails.get(u):
            print u, "{0}{1}".format(index,"@a.com")
            index += 1
